---
title: "Preprocessing, Persian Rugs"
author:
- name: Elyas Heidari
  affiliation:
  - Department of Biological Systems Sciences and Engineering, ETH Zurich, Switzerland 
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  workflowr::wflow_html:
    code_folding: hide
    toc: true
    toc_float: true
    number_sections: false
---

<!-- 2020-05-29 07:51 -->
<!-- elihei  [<eheidari@student.ethz.ch>]-->
<!--/Volumes/Projects/SLF_rugs/analysis/0-preprocessing.Rmd-->

## Setup

```{r setup, include = FALSE}
library('BiocStyle')
knitr::opts_chunk$set(autodep=TRUE, cache=TRUE, dev='png', cache.lazy = FALSE)
# wflow_build(files='analysis/0-preprocessing.Rmd', view=F, verbose=T, delete_cache=F, cache.lazy = FALSE)
```

## Init
```{r init, message=FALSE, warning=FALSE, paged.print=FALSE, echo=F}
source('code/utils.R')
raw_tag  = 'rugs_data.xlsx'
data_raw = 'data_raw'
out_dir  = 'output'
```

## Preprocess data

```{r preproc, message=FALSE, warning=FALSE, paged.print=FALSE, echo=F}
rugs_data = file.path(data_raw, raw_tag) %>%  
    read.xlsx(., sheetIndex=1) %>%
    as.data.table

rugs_data %<>% 
    .[, group   := gsub('Option ', '', group)] %>%
    .[!is.na(group)] %>%
    .[, age     := factor(age, ordered=T, 
        levels=c('< 15', '15-20', '21-30', '30-40', '> 40'))] %>%
    .[age != '< 15'] %>%
    .[, age  := droplevels(age)] %>%
    .[, degree  := str_sub(degree, 1, 3)] %>%
    .[, degree  := factor(degree, ordered=T, 
        levels=c('Oth', 'Col', 'Bac', 'Mas', 'MD/'))] %>%
    .[degree != 'Oth'] %>%
    .[degree == 'Col', degree := 'Diploma'] %>%
    .[degree == 'Bac', degree := 'BSc/BA'] %>%
    .[degree == 'Mas', degree := 'MSc/MA'] %>%
    .[degree == 'MD/', degree := 'PhD/MD'] %>%
    .[, degree  := droplevels(degree)] %>%
    .[, field   := factor(str_sub(field, 1, 3))] %>%
    .[, persian := ifelse(persian == 'Yes', 'Persian', 'non-Persian')] %>%
    setnames('persian', 'nationality') %>%
    .[, nationality := factor(nationality, ordered=T,
        levels=c('Persian', 'non-Persian'))] %>%
    .[, persian_art := factor(persian_art, ordered=T, 
        levels=c('No', 'A little', 'Yes'))] %>%
    .[, form    := factor(str_sub(form, 1, 3))] %>%
    .[, bored   := factor(bored, ordered=T, 
        levels=c('No', 'Maybe', 'Yes'))] %>%
    .[, curse   := ifelse(grepl('Yeah', curse), 'Yes', 'No')] %>%
    .[, curse   := factor(curse, ordered=T, levels=c('No', 'Yes'))] %>%
    .[, score   := (Bakhtiari  == 'Bakhtiari') +
                   (Balouch    == 'Balouch') +
                   (Qashqai    == 'Qashqai') +
                   (Kurd       == 'Kurd')] 

features = data.table(title=c('group', 'degree', 'field', 'age','nationality', 'persian_art', 'bored', 'curse'), 
    text=c('Experimental Group', 'Academic Degree', 'Academic Field', 'Age Group', 'Nationality', 'Familiarity', 'Bored', 'Curse')) %>% setkey(title)

plot_features = c('nationality', 'age', 'degree', 'field', 'curse', 'bored', 'persian_art')
```

## Overall summary
```{r summ, message=FALSE, warning=FALSE, paged.print=FALSE}
group_pie = pie_chart('group') + ggtitle('')

rugs_sum = rugs_data[, .(mean_score = mean(score), 
    ci_score = sd(score)/sqrt(length(score)) * qt((1-0.05)/2 + .5, length(score)-1)),
    by=c('group')] %>%
    .[, ci_score := ifelse(ci_score > mean_score, 0, ci_score)]

bar_plot = rugs_sum %>% ggplot + 
aes_string(x='group', y='mean_score', fill='group') +
geom_bar(stat='identity', position=position_dodge(), color='black')  +
geom_errorbar(aes(ymin=mean_score-ci_score, ymax=mean_score+ci_score), width=0.1,
             position=position_dodge(.9)) +
scale_fill_viridis_d() +
theme_bw() +
labs(x='')

ov_plot = group_pie + bar_plot
ggsave(file.path(out_dir, 'ov_plot.pdf'), ov_plot)
```

## Conditioned summary
```{r plots, message=FALSE, warning=FALSE, paged.print=FALSE, echo=F}
pies = plot_features %>% map(pie_chart) 

dens = plot_features %>% map(dens_plot) 
dens[2:7] %<>% map(function(x) x + labs(x='', y=''))

bar = plot_features %>% map(bar_plot)
bar1 = bar %>% map(function(x) x$bar1)
bar2 = bar %>% map(function(x) x$bar2)
bar1[[1]] = bar1[[1]] + labs(x='')
bar1[2:7] = (2:7) %>% map(function(x) bar1[[x]] + labs(x='', y=''))
bar2[2:7] = (2:7) %>% map(function(x) bar2[[x]] + labs(x='', y=''))

plt = list(pies, dens, bar1, bar2) %>% purrr::reduce(append) %>% purrr::reduce(`+`)

final_plot = (plt) + 
    plot_layout(guides = 'collect', heights = c(15, 30, 15, 15), ncol = 7, widths=rep(25, 7)) 

ggsave(file.path(out_dir, 'summ_plot.pdf'), final_plot, width = 25, height = 12)
```

## Hypothesis tests 
```{r tests, message=FALSE, warning=FALSE, paged.print=FALSE}
pairwise.wilcox.test(rugs_data$score, rugs_data$group, p.adjust.method = p.adjust.methods)

feature_titles = setdiff(features$title, 'group') 

res = feature_titles %>%
    map(p_value) %>% 
    purrr::reduce(rbind) %>%
    as.data.table %>%
    setnames(c('group 1', 'group 2', 'group 3', 'unconditioned')) %>%
    .[, `individual feature` := ..features[feature_titles]$text] %>%
    .[, c(5, 1:4)]

fwrite(res, 'data_tidy/test_res.txt')
```

<!-- ```{r confusion, message=FALSE, warning=FALSE, paged.print=FALSE}
classes  = c('Bakhtiari', 'Balouch', 'Kurd', 'Qashqai')
conf_grp <- function(grp){
    conf_mtx = rugs_data %>%
    .[group==grp] %>%
    .[, lapply(.SD, table), .SDcols=classes] %>%
    setnames(paste0(classes[1], '.V1'), 'class') %>%
    .[, .SD, .SDcols=-(names(.) %like% 'V1')] %>%
    setnames(names(.), gsub('\\.N', '', names(.))) %>%
    .[,-1] %>%
    as.matrix 
    # diag(conf_mtx) = 0
    # conf_mtx = t(apply(conf_mtx, 1, function(x) 5-rank(x)))
    conf_mtx = t(apply(conf_mtx, 1, function(x) x/sum(x)))
    rownames(conf_mtx) = colnames(conf_mtx1)
    conf_mtx
}
# conf_mtc = c('Persian', 'non-Persian') %>% map(conf_grp)
conf_mtc = 1:3 %>% map(conf_grp)

hm_obj   = Heatmap(                                        
    matrix=conf_mtx1, col=viridis(2),                     
    cluster_rows = FALSE, cluster_columns = FALSE,
    name="1/#clusters",
    row_names_side="left",          
    show_column_names=TRUE,
    column_title = 'Sample Abundances' 
)  
``` -->
